version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: restaurant_reservation_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    image: thiagomag/fiap-pagamento-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiap-pagamento-service
    ports:
      - "8083:8083"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: pagamento-service
      DB_URL_PARAM: ?ssl=false
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
